[project]
name = "docx_generator"
version = "0.1.0"
description = "Un server MCP per generare file Docx da un testo."
requires-python = "~=3.12"

dependencies = [
    "mcp~=1.1.3",
    "pydantic~=2.8",
    "pypandoc",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"